Fixed 'AttributeError' in server/importer.py
